### ISSUE TITLE
Frontend needs to have a dynamic slug page for each entry

### ISSUE THREAD

**Issue by GrowTec** [GrowTec/knowledgebase#3]
Add a slug for knowledge entries. This allows for all entries to use the same page template, but to also dynamically pull in data for a particular entry ID.

https://kit.svelte.dev/docs#routing-pages

**Comment by andrewguest** [comment]
I'll work on this and #5 today. Should be able to get them both done today.

**Comment by GrowTec** [comment]
Thanks! I was going to start looking at them, but if you've already got everything setup to continue working on those then go for it.
